services:
  redis:
    image: redis:latest  # Используем последнюю версию Redis
    container_name: redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]  # Отключаем постоянное сохранение данных
    ports:
      - "6380:6379"  # Пробрасываем порт 6379
  db:
    image: postgres:16.2-alpine
    container_name: db
    restart: on-failure
    environment:
      - 'TZ=GMT+3'
      - 'PGTZ=GMT+3'
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
    ports:
      - "5433:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  web:
    container_name: payment_app
    build:
      context: ./
      dockerfile: ./DockerfileFastApi
    restart: on-failure
    depends_on:
      - db
      - redis
    volumes:
      - ./payment_app/templates:/code/fastapi_app/templates
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  bot:
    container_name: bot_app
    build:
      context: ./
      dockerfile: DockerfileBot
    restart: on-failure
    depends_on:
      - db
      - web
      - redis
    volumes:
      - ./mj_results:/code/tgbot_app/mj_results
      - ./tgbot_app/logs:/code/tgbot_app/logs
      - ./tgbot_app/migrations/versions:/code/tgbot_app/migrations/versions
    command: bash -c "cd /code/tgbot_app && alembic upgrade head && python main.py"

    # command: sh -c "alembic upgrade head && chmod +x ./bash.sh && python main.py"

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: on-failure
    depends_on:
      - web
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certs:/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  pg_data:
    driver: local